### ISSUE TITLE
这个现在是不是不能用了？

### ISSUE THREAD

**Issue by 8824PPZ** [PKUOriginalFire/DanmakuDangan#3]
```
[2024-03-07 10:46:13.390] [error] Unhandled Exception UnhandledRejection Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Zs (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:9:35064)
    at lu (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:979)
    at D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:3780
[2024-03-07 10:46:19.291] [error] Unhandled Exception UnhandledRejection Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Zs (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:9:35064)
    at lu (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:979)
    at D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:3780
[2024-03-07 10:46:30.461] [error] Unhandled Exception UnhandledRejection Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Zs (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:9:35064)
    at lu (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:979)
    at D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:3780
[2024-03-07 10:48:11.981] [error] Unhandled Exception UnhandledRejection Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Zs (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:9:35064)
    at lu (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:979)
    at D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:3780
```

**Comment by FrandreJoestar** [comment]
> ```
> [2024-03-07 10:46:13.390] [error] Unhandled Exception UnhandledRejection Error: Project name could not be inferred. Please specify the `projectName` option.
>     at new Zs (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:9:35064)
>     at lu (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:979)
>     at D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:3780
> [2024-03-07 10:46:19.291] [error] Unhandled Exception UnhandledRejection Error: Project name could not be inferred. Please specify the `projectName` option.
>     at new Zs (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:9:35064)
>     at lu (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:979)
>     at D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:3780
> [2024-03-07 10:46:30.461] [error] Unhandled Exception UnhandledRejection Error: Project name could not be inferred. Please specify the `projectName` option.
>     at new Zs (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:9:35064)
>     at lu (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:979)
>     at D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:3780
> [2024-03-07 10:48:11.981] [error] Unhandled Exception UnhandledRejection Error: Project name could not be inferred. Please specify the `projectName` option.
>     at new Zs (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:9:35064)
>     at lu (D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:979)
>     at D:\元火弹幕机\danmaku-dangan\resources\app.asar\out\main\index.js:50:3780
> ```

哥们解决了吗？

**Comment by Wybxc** [comment]
这个项目已经很久没更新了，比较新的是 https://github.com/PKUOriginalFire/DanmakuLight 和 https://github.com/PKUOriginalFire/danmaku-server
